"use client";

import { useEffect, useState } from "react";
import { apriAllegato, caricaAllegati, caricaAllegato, eliminaAllegato } from "@/lib/rappresentanti/api";
import type { AllegatoRappresentante } from "@/lib/rappresentanti/types";
import { formattaDataIt } from "@/lib/rappresentanti/utils";
import { EmptyState, Toast, inputClass, primaryButton, secondaryButton } from "./Common";

function formatBytes(bytes: number) { if (!bytes) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** i).toFixed(i ? 1 : 0)} ${units[i]}`; }

export default function AttachmentsManager({ owner }: { owner: { rappresentante_id?: string; azienda_id?: string; prodotto_id?: string } }) {
  const [items, setItems] = useState<AllegatoRappresentante[]>([]); const [file, setFile] = useState<File | null>(null); const [categoria, setCategoria] = useState("altro"); const [busy, setBusy] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const load = () => caricaAllegati(owner).then(setItems).catch((e) => setToast({ message: e.message, error: true }));
  useEffect(() => { load(); }, [owner.rappresentante_id, owner.azienda_id, owner.prodotto_id]);
  async function upload() { if (!file) return; setBusy(true); try { await caricaAllegato(file, owner, categoria); setFile(null); await load(); setToast({ message: "Allegato caricato." }); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore caricamento.", error: true }); } finally { setBusy(false); } }
  return <div className="space-y-5"><div className="grid gap-3 rounded-2xl border border-[#2B2F5E]/8 bg-white p-4 sm:grid-cols-[1fr_180px_auto]"><input type="file" className={`${inputClass} file:mr-3 file:rounded-lg file:border-0 file:bg-[#5E9AD3]/10 file:px-3 file:py-1 file:text-xs file:font-semibold file:text-[#2D80B3]`} onChange={(e) => setFile(e.target.files?.[0] || null)} /><select className={inputClass} value={categoria} onChange={(e) => setCategoria(e.target.value)}><option value="catalogo">Catalogo</option><option value="listino">Listino</option><option value="scheda_tecnica">Scheda tecnica</option><option value="brochure">Brochure</option><option value="biglietto_visita">Biglietto da visita</option><option value="immagine">Immagine</option><option value="altro">Altro</option></select><button type="button" disabled={!file || busy} className={primaryButton} onClick={upload}>{busy ? "Caricamento..." : "Carica"}</button><p className="text-xs text-[#2B2F5E]/45 sm:col-span-3">Dimensione massima 50 MB. I file sono conservati nell’archivio privato.</p></div>{items.length === 0 ? <EmptyState title="Nessun allegato presente." /> : <div className="overflow-x-auto rounded-2xl border border-[#2B2F5E]/8 bg-white"><table className="min-w-[720px] w-full text-sm"><thead className="bg-[#F7F8FA] text-left text-xs text-[#2B2F5E]/55"><tr><th className="p-3">Nome</th><th className="p-3">Tipo</th><th className="p-3">Dimensione</th><th className="p-3">Caricato il</th><th className="p-3 text-right">Azioni</th></tr></thead><tbody className="divide-y divide-[#2B2F5E]/8">{items.map((item) => <tr key={item.id}><td className="p-3 font-medium text-[#2B2F5E]">{item.nome}</td><td className="p-3 capitalize text-[#2B2F5E]/65">{item.categoria_documento.replaceAll("_", " ")}</td><td className="p-3 text-[#2B2F5E]/65">{formatBytes(item.dimensione)}</td><td className="p-3 text-[#2B2F5E]/65">{formattaDataIt(item.created_at)}</td><td className="p-3"><div className="flex justify-end gap-2"><button type="button" className={`${secondaryButton} min-h-9 py-1.5 text-xs`} onClick={() => apriAllegato(item)}>Apri</button><button type="button" className="min-h-9 rounded-xl px-3 text-xs font-semibold text-red-600 hover:bg-red-50" onClick={async () => { if (!confirm(`Eliminare ${item.nome}?`)) return; await eliminaAllegato(item); await load(); }}>Elimina</button></div></td></tr>)}</tbody></table></div>}{toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}</div>;
}
