"use client";

import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import LayoutApp from "@/components/LayoutApp";
import AttachmentsManager from "@/components/rappresentanti/AttachmentsManager";
import ContactHistoryTimeline from "@/components/rappresentanti/ContactHistoryTimeline";
import { BadgeList, Breadcrumb, EmptyState, LoadingSkeleton, Modal, SectionCard, StatusBadge, Toast, inputClass, primaryButton, secondaryButton } from "@/components/rappresentanti/Common";
import { aggiungiNota, caricaNote, caricaRappresentante, eliminaNota, eliminaRappresentante } from "@/lib/rappresentanti/api";
import type { NotaRappresentante, Rappresentante } from "@/lib/rappresentanti/types";
import { formattaDataIt, inizialiRappresentante } from "@/lib/rappresentanti/utils";

const tabs = ["Panoramica", "Aziende e prodotti", "Cronologia contatti", "Note", "Allegati"] as const;

export default function RepresentativeDetails({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ contatto?: string }> }) {
  const { id } = use(params); const query = use(searchParams); const router = useRouter();
  const [itemState, setItem] = useState<Rappresentante | null>(null); const [tab, setTab] = useState<(typeof tabs)[number]>(query.contatto ? "Cronologia contatti" : "Panoramica"); const [notes, setNotes] = useState<NotaRappresentante[]>([]); const [note, setNote] = useState(""); const [deleteOpen, setDeleteOpen] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null); const [loading, setLoading] = useState(true);
  const load = () => caricaRappresentante(id).then(setItem).catch((e) => setToast({ message: e.message, error: true })).finally(() => setLoading(false));
  const loadNotes = () => caricaNote(id).then(setNotes).catch((e) => setToast({ message: e.message, error: true }));
  useEffect(() => { load(); loadNotes(); }, [id]);
  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); setToast({ message: `${label} copiato.` }); };

  if (loading) return <LayoutApp><LoadingSkeleton rows={6} /></LayoutApp>;
  if (!itemState) return <LayoutApp><EmptyState title="Rappresentante non trovato." /></LayoutApp>;
  const item = itemState as Rappresentante & {
    cellulare: string;
    telefono_secondario: string;
    email: string;
    email_secondaria: string;
    sito_web: string;
    linkedin_url: string;
  };
  const aziendeBadges = item.aziende.map((x) => ({ id: x.azienda.id, label: x.azienda.nome_commerciale || x.azienda.ragione_sociale }));
  return <LayoutApp><Breadcrumb items={[{ label: "Rubrica", href: "/rubrica/rappresentanti" }, { label: "Rappresentanti", href: "/rubrica/rappresentanti" }, { label: `${item.nome} ${item.cognome}` }]} />
    <div className="mb-6 rounded-2xl border border-[#2B2F5E]/8 bg-white p-5 shadow-sm sm:p-6">
      <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-start"><div className="flex items-start gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-[#5E9AD3]/12 text-lg font-bold text-[#2D80B3]">{item.avatar_url ? <img src={item.avatar_url} alt="" className="h-full w-full object-cover" /> : inizialiRappresentante(item.nome, item.cognome)}</div><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold text-[#2B2F5E]">{item.nome} {item.cognome}</h1><StatusBadge active={item.active} /></div><p className="mt-1 text-sm text-[#2B2F5E]/55">{item.ruolo || "Ruolo non indicato"} · {item.area_competenza || item.regione || "Area non indicata"}</p><div className="mt-3"><BadgeList items={aziendeBadges} max={4} /></div></div></div>
        <div className="flex flex-wrap gap-2"><a className={primaryButton} href={`/rubrica/rappresentanti/${id}/modifica`}>Modifica</a>{item.cellulare && <a className={secondaryButton} href={`tel:${item.cellulare}`}>Chiama</a>}{item.email && <a className={secondaryButton} href={`mailto:${item.email}`}>Invia email</a>}<button type="button" className={secondaryButton} onClick={() => setTab("Cronologia contatti")}>Registra contatto</button><button type="button" className={secondaryButton} onClick={() => setTab("Note")}>Aggiungi nota</button><button type="button" className={secondaryButton} onClick={() => setTab("Allegati")}>Carica allegato</button><button type="button" className={secondaryButton} onClick={() => window.print()}>Stampa</button><button type="button" className="min-h-11 rounded-xl px-3 text-sm font-semibold text-red-600 hover:bg-red-50" onClick={() => setDeleteOpen(true)}>Elimina</button></div>
      </div>
    </div>
    <div className="mb-5 overflow-x-auto rounded-2xl border border-[#2B2F5E]/8 bg-white p-2"><div className="flex min-w-max gap-1">{tabs.map((x) => <button key={x} type="button" onClick={() => setTab(x)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${tab === x ? "bg-[#2B2F5E] text-white" : "text-[#2B2F5E] hover:bg-[#F2F2F2]"}`}>{x}</button>)}</div></div>

    {tab === "Panoramica" && <div className="grid gap-4 xl:grid-cols-3"><SectionCard title="Recapiti" className="xl:col-span-1"><dl className="space-y-3 text-sm">{[["Cellulare", item.cellulare], ["Secondo telefono", item.telefono_secondario], ["Email", item.email], ["Seconda email", item.email_secondaria], ["Sito web", item.sito_web], ["LinkedIn", item.linkedin_url]].map(([label, value]) => <div key={label}><dt className="text-xs text-[#2B2F5E]/45">{label}</dt><dd className="mt-0.5 flex items-center gap-2 break-all font-medium text-[#2B2F5E]">{value ? (label.includes("Email") ? <a href={`mailto:${value}`} className="hover:text-[#2D80B3]">{value}</a> : label.includes("telefono") || label === "Cellulare" ? <a href={`tel:${value}`} className="hover:text-[#2D80B3]">{value}</a> : <a href={value} target="_blank" rel="noreferrer" className="hover:text-[#2D80B3]">{value}</a>) : "—"}{value && <button type="button" onClick={() => copy(value, label)} className="text-[10px] font-semibold text-[#2D80B3]">Copia</button>}</dd></div>)}</dl></SectionCard>
      <SectionCard title="Informazioni" className="xl:col-span-1"><dl className="grid gap-3 text-sm"><Info label="Indirizzo" value={[item.indirizzo, item.cap, item.comune, item.provincia].filter(Boolean).join(", ")} /><Info label="Area geografica" value={item.area_competenza || item.zona_commerciale} /><Info label="Province servite" value={item.province_servite.join(", ")} /><Info label="Contatto preferito" value={item.modalita_contatto_preferita} /><Info label="Sopralluoghi" value={item.disponibilita_sopralluoghi ? "Disponibile" : "Non disponibile"} /><Info label="Interesse / priorità" value={`${item.livello_interesse} / ${item.priorita}`} /></dl></SectionCard>
      <SectionCard title="Categorie e prodotti" className="xl:col-span-1"><p className="mb-2 text-xs text-[#2B2F5E]/45">Categorie principali</p><BadgeList items={item.categorie.map((x) => ({ id: x.id, label: x.nome, color: x.colore }))} max={5} /><p className="mb-2 mt-5 text-xs text-[#2B2F5E]/45">Prodotti principali</p><BadgeList items={item.prodotti.map((x) => ({ id: x.id, label: x.nome }))} max={5} /></SectionCard>
      <SectionCard title="Note sintetiche" className="xl:col-span-2"><p className="whitespace-pre-wrap text-sm leading-6 text-[#2B2F5E]/75">{item.note_generali || item.note_commerciali || "Nessuna nota presente."}</p></SectionCard><SectionCard title="Dati scheda"><dl className="space-y-3"><Info label="Inserito il" value={formattaDataIt(item.created_at)} /><Info label="Ultimo aggiornamento" value={formattaDataIt(item.updated_at)} /><Info label="Ultimo contatto" value={formattaDataIt(item.ultimo_contatto_at)} /><Info label="Prossimo ricontatto" value={formattaDataIt(item.prossimo_ricontatto_at)} /></dl></SectionCard></div>}

    {tab === "Aziende e prodotti" && <div className="space-y-4">{item.aziende.length === 0 ? <EmptyState title="Nessuna azienda associata." /> : item.aziende.map((rel) => <SectionCard key={rel.id} title={rel.azienda.nome_commerciale || rel.azienda.ragione_sociale} description={rel.azienda.descrizione || undefined} actions={<StatusBadge active={rel.active} label={rel.stato_collaborazione} />}><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><div className="space-y-2 text-sm"><Info label="Sito" value={rel.azienda.sito_web} link /><Info label="Email" value={rel.azienda.email} /><Info label="Telefono" value={rel.azienda.telefono} /><Info label="Referente" value={rel.referente_interno} /><Info label="Area territoriale" value={rel.area_territoriale} /><Info label="Collaborazione" value={`${formattaDataIt(rel.data_inizio)} – ${formattaDataIt(rel.data_fine)}`} />{rel.note && <Info label="Note" value={rel.note} />}</div><div><div className="mb-3"><BadgeList items={rel.azienda.categorie.map((x) => ({ id: x.id, label: x.nome, color: x.colore }))} max={6} /></div>{rel.prodotti.length === 0 ? <p className="rounded-xl bg-[#F7F8FA] p-4 text-sm text-[#2B2F5E]/55">Nessun prodotto associato a questa collaborazione.</p> : <div className="overflow-x-auto rounded-xl border border-[#2B2F5E]/8"><table className="min-w-[560px] w-full text-sm"><thead className="bg-[#F7F8FA] text-left text-xs text-[#2B2F5E]/55"><tr><th className="p-3">Prodotto</th><th className="p-3">Codice</th><th className="p-3">Categorie</th><th className="p-3">Stato</th></tr></thead><tbody>{rel.prodotti.map((p) => <tr key={p.id} className="border-t border-[#2B2F5E]/8"><td className="p-3"><p className="font-medium text-[#2B2F5E]">{p.nome}</p><p className="text-xs text-[#2B2F5E]/45">{p.descrizione}</p></td><td className="p-3">{p.codice || "—"}</td><td className="p-3"><BadgeList items={p.categorie.map((x) => ({ id: x.id, label: x.nome, color: x.colore }))} /></td><td className="p-3"><StatusBadge active={p.active} /></td></tr>)}</tbody></table></div>}</div></div></SectionCard>)}</div>}
    {tab === "Cronologia contatti" && <ContactHistoryTimeline rappresentanteId={id} openForm={Boolean(query.contatto)} onRecorded={load} />}
    {tab === "Note" && <div className="space-y-4"><SectionCard title="Aggiungi nota"><textarea className={`${inputClass} min-h-28`} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Scrivi una nota..." /><div className="mt-3 flex justify-end"><button type="button" disabled={!note.trim()} className={primaryButton} onClick={async () => { await aggiungiNota(id, note); setNote(""); await loadNotes(); setToast({ message: "Nota aggiunta." }); }}>Aggiungi nota</button></div></SectionCard>{notes.length === 0 ? <EmptyState title="Nessuna nota presente." /> : notes.map((n) => <SectionCard key={n.id}><div className="flex items-start justify-between gap-4"><div><p className="whitespace-pre-wrap text-sm leading-6 text-[#2B2F5E]/75">{n.testo}</p><p className="mt-2 text-xs text-[#2B2F5E]/40">{new Date(n.created_at).toLocaleString("it-IT")}</p></div><button type="button" onClick={async () => { await eliminaNota(n.id); await loadNotes(); }} className="text-xs font-semibold text-red-600">Elimina</button></div></SectionCard>)}</div>}
    {tab === "Allegati" && <AttachmentsManager owner={{ rappresentante_id: id }} />}
    {deleteOpen && <Modal title="Eliminare il rappresentante?" onClose={() => setDeleteOpen(false)}><p className="text-sm text-[#2B2F5E]/70">La scheda verrà archiviata con eliminazione logica. Aziende e prodotti resteranno disponibili.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={secondaryButton} onClick={() => setDeleteOpen(false)}>Annulla</button><button type="button" className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white" onClick={async () => { await eliminaRappresentante(id); router.push("/rubrica/rappresentanti"); }}>Elimina</button></div></Modal>}
    {toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}
  </LayoutApp>;
}

function Info({ label, value, link = false }: { label: string; value: string | number | null | undefined; link?: boolean }) { return <div><dt className="text-xs text-[#2B2F5E]/45">{label}</dt><dd className="mt-0.5 break-words text-sm font-medium capitalize text-[#2B2F5E]">{value ? link ? <a href={String(value)} target="_blank" rel="noreferrer" className="text-[#2D80B3] hover:underline">{value}</a> : value : "—"}</dd></div>; }
