"use client";

import { useEffect, useMemo, useState } from "react";
import LayoutApp from "@/components/LayoutApp";
import { CompanyFormModal } from "@/components/rappresentanti/EntityForms";
import { BadgeList, Breadcrumb, EmptyState, LoadingSkeleton, Modal, PageHeader, StatCard, StatusBadge, Toast, inputClass, primaryButton, secondaryButton } from "@/components/rappresentanti/Common";
import { caricaAziende, caricaCategorie, caricaProdotti, caricaRappresentanti, eliminaAzienda } from "@/lib/rappresentanti/api";
import type { AziendaRappresentata, CategoriaRappresentante, ProdottoRappresentato, Rappresentante } from "@/lib/rappresentanti/types";

export default function CompaniesPage() {
  const [items, setItems] = useState<AziendaRappresentata[]>([]); const [categories, setCategories] = useState<CategoriaRappresentante[]>([]); const [products, setProducts] = useState<ProdottoRappresentato[]>([]); const [representatives, setRepresentatives] = useState<Rappresentante[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<AziendaRappresentata | "new" | null>(null); const [deleting, setDeleting] = useState<AziendaRappresentata | null>(null); const [loading, setLoading] = useState(true); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const load = () => Promise.all([caricaAziende(), caricaCategorie(false), caricaProdotti(), caricaRappresentanti()]).then(([a, c, p, r]) => { setItems(a); setCategories(c); setProducts(p); setRepresentatives(r); }).catch((e) => setToast({ message: e.message, error: true })).finally(() => setLoading(false)); useEffect(() => { load(); }, []);
  const filtered = useMemo(() => items.filter((x) => [x.ragione_sociale, x.nome_commerciale, x.partita_iva, x.comune, x.regione, x.email, ...x.categorie.map((c) => c.nome)].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase())), [items, search]);
  const repCount = (id: string) => representatives.filter((r) => r.aziende.some((a) => a.azienda_id === id)).length; const productCount = (id: string) => products.filter((p) => p.azienda_id === id).length;
  return <LayoutApp><Breadcrumb items={[{ label: "Rubrica rappresentanti", href: "/rubrica/rappresentanti" }, { label: "Aziende rappresentate" }]} /><PageHeader title="Aziende rappresentate" subtitle="Anagrafiche indipendenti delle aziende, con prodotti e rappresentanti collegati." actions={<button type="button" className={primaryButton} onClick={() => setEditing("new")}>Nuova azienda</button>} /><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><StatCard label="Aziende totali" value={items.length} /><StatCard label="Aziende attive" value={items.filter((x) => x.active).length} tone="green" /><StatCard label="Prodotti collegati" value={products.length} tone="gold" /></div><input className={`${inputClass} mb-4`} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cerca ragione sociale, P.IVA, località o categoria..." />
    {loading ? <LoadingSkeleton rows={5} /> : filtered.length === 0 ? <EmptyState title="Nessuna azienda trovata." actionLabel={!items.length ? "Aggiungi la prima azienda" : undefined} onAction={!items.length ? () => setEditing("new") : undefined} /> : <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{filtered.map((x) => <article key={x.id} className="rounded-2xl border border-[#2B2F5E]/8 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3">{x.logo_url ? <img src={x.logo_url} alt="" className="h-11 w-11 rounded-xl object-contain" /> : <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#5E9AD3]/10 font-bold text-[#2D80B3]">{x.ragione_sociale.charAt(0)}</span>}<div className="min-w-0"><a href={`/rubrica/rappresentanti/aziende/${x.id}`} className="font-semibold text-[#2B2F5E] hover:text-[#2D80B3]">{x.nome_commerciale || x.ragione_sociale}</a>{x.nome_commerciale && <p className="truncate text-xs text-[#2B2F5E]/45">{x.ragione_sociale}</p>}</div></div><StatusBadge active={x.active} /></div><div className="mt-4"><BadgeList items={x.categorie.map((c) => ({ id: c.id, label: c.nome, color: c.colore }))} max={3} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-[#2B2F5E]/45">Sede</dt><dd className="mt-0.5 font-medium text-[#2B2F5E]">{[x.comune, x.provincia].filter(Boolean).join(" · ") || "—"}</dd></div><div><dt className="text-[#2B2F5E]/45">P.IVA</dt><dd className="mt-0.5 font-medium text-[#2B2F5E]">{x.partita_iva || "—"}</dd></div><div><dt className="text-[#2B2F5E]/45">Rappresentanti</dt><dd className="mt-0.5 font-medium text-[#2B2F5E]">{repCount(x.id)}</dd></div><div><dt className="text-[#2B2F5E]/45">Prodotti</dt><dd className="mt-0.5 font-medium text-[#2B2F5E]">{productCount(x.id)}</dd></div></dl><div className="mt-5 flex gap-2 border-t border-[#2B2F5E]/8 pt-4"><a href={`/rubrica/rappresentanti/aziende/${x.id}`} className={`${secondaryButton} min-h-9 py-1.5 text-xs`}>Dettaglio</a><button type="button" className={`${secondaryButton} min-h-9 py-1.5 text-xs`} onClick={() => setEditing(x)}>Modifica</button><button type="button" onClick={() => setDeleting(x)} className="ml-auto min-h-9 rounded-xl px-3 text-xs font-semibold text-red-600 hover:bg-red-50">Elimina</button></div></article>)}</div>}
    {editing && <CompanyFormModal initial={editing === "new" ? undefined : editing} categories={categories} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); setToast({ message: "Azienda salvata." }); }} />}
    {deleting && <Modal title="Eliminare l’azienda?" onClose={() => setDeleting(null)}><p className="text-sm text-[#2B2F5E]/70">L’azienda può essere eliminata solo se non è collegata a rappresentanti. I prodotti collegati devono essere gestiti prima dell’eliminazione.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={secondaryButton} onClick={() => setDeleting(null)}>Annulla</button><button type="button" className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white" onClick={async () => { try { await eliminaAzienda(deleting.id); setDeleting(null); await load(); setToast({ message: "Azienda eliminata." }); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore eliminazione.", error: true }); } }}>Elimina</button></div></Modal>}
    {toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}</LayoutApp>;
}
