"use client";

import { useEffect, useState } from "react";
import LayoutApp from "@/components/LayoutApp";
import { Breadcrumb, EmptyState, FormField, LoadingSkeleton, Modal, PageHeader, StatusBadge, Toast, inputClass, primaryButton, secondaryButton } from "@/components/rappresentanti/Common";
import { caricaCategorie, eliminaCategoria, riordinaCategorie, salvaCategoria } from "@/lib/rappresentanti/api";
import type { CategoriaRappresentante } from "@/lib/rappresentanti/types";

const empty = { nome: "", descrizione: "", colore: "#5E9AD3", parent_id: "", active: true };

export default function CategoriesPage() {
  const [items, setItems] = useState<CategoriaRappresentante[]>([]); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<CategoriaRappresentante | "new" | null>(null); const [form, setForm] = useState(empty); const [deleting, setDeleting] = useState<CategoriaRappresentante | null>(null); const [replacement, setReplacement] = useState(""); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const load = () => caricaCategorie(true).then(setItems).catch((e) => setToast({ message: e.message, error: true })).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  function open(item?: CategoriaRappresentante) { setEditing(item || "new"); setForm(item ? { nome: item.nome, descrizione: item.descrizione || "", colore: item.colore, parent_id: item.parent_id || "", active: item.active } : empty); }
  async function save() { if (!form.nome.trim()) return; try { await salvaCategoria({ ...form, parent_id: form.parent_id || null, ordine: editing !== "new" && editing ? editing.ordine : (items.length + 1) * 10 }, editing !== "new" && editing ? editing.id : undefined); setEditing(null); await load(); setToast({ message: "Categoria salvata." }); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore salvataggio.", error: true }); } }
  async function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= items.length) return; const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; setItems(copy); try { await riordinaCategorie(copy); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore riordino.", error: true }); await load(); } }
  const linked = deleting ? (deleting.conteggio_rappresentanti || 0) + (deleting.conteggio_aziende || 0) + (deleting.conteggio_prodotti || 0) : 0;
  return <LayoutApp><Breadcrumb items={[{ label: "Rubrica rappresentanti", href: "/rubrica/rappresentanti" }, { label: "Gestione categorie" }]} /><PageHeader title="Gestione categorie rappresentanti" subtitle="Crea, organizza e disattiva categorie e sottocategorie merceologiche." actions={<button type="button" className={primaryButton} onClick={() => open()}>Nuova categoria</button>} />
    {loading ? <LoadingSkeleton rows={6} /> : items.length === 0 ? <EmptyState title="Nessuna categoria presente." actionLabel="Crea la prima categoria" onAction={() => open()} /> : <div className="space-y-2">{items.map((item, index) => { const parent = items.find((x) => x.id === item.parent_id); return <div key={item.id} className={`grid gap-3 rounded-2xl border border-[#2B2F5E]/8 bg-white p-4 shadow-sm md:grid-cols-[auto_1fr_auto_auto] md:items-center ${item.parent_id ? "ml-4 sm:ml-10" : ""}`}><div className="flex gap-1"><button type="button" disabled={index === 0} onClick={() => move(index, -1)} title="Sposta su" className="h-8 w-8 rounded-lg border border-[#2B2F5E]/10 text-xs disabled:opacity-30">↑</button><button type="button" disabled={index === items.length - 1} onClick={() => move(index, 1)} title="Sposta giù" className="h-8 w-8 rounded-lg border border-[#2B2F5E]/10 text-xs disabled:opacity-30">↓</button></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="h-3 w-3 rounded-full" style={{ backgroundColor: item.colore }} /><p className="font-semibold text-[#2B2F5E]">{item.nome}</p>{parent && <span className="text-xs text-[#2B2F5E]/45">Sottocategoria di {parent.nome}</span>}<StatusBadge active={item.active} /></div><p className="mt-1 truncate text-xs text-[#2B2F5E]/50">{item.descrizione || "Nessuna descrizione"}</p></div><div className="flex flex-wrap gap-2 text-[11px] text-[#2B2F5E]/60"><span className="rounded-full bg-[#F2F2F2] px-2.5 py-1">{item.conteggio_rappresentanti || 0} rappresentanti</span><span className="rounded-full bg-[#F2F2F2] px-2.5 py-1">{item.conteggio_aziende || 0} aziende</span><span className="rounded-full bg-[#F2F2F2] px-2.5 py-1">{item.conteggio_prodotti || 0} prodotti</span></div><div className="flex gap-2"><button type="button" className={`${secondaryButton} min-h-9 py-1.5 text-xs`} onClick={() => open(item)}>Modifica</button><button type="button" onClick={async () => { await salvaCategoria({ nome: item.nome, descrizione: item.descrizione, colore: item.colore, parent_id: item.parent_id, ordine: item.ordine, active: !item.active }, item.id); await load(); }} className={`${secondaryButton} min-h-9 py-1.5 text-xs`}>{item.active ? "Disattiva" : "Attiva"}</button><button type="button" onClick={() => { setDeleting(item); setReplacement(""); }} className="min-h-9 rounded-xl px-3 text-xs font-semibold text-red-600 hover:bg-red-50">Elimina</button></div></div>; })}</div>}
    {editing && <Modal title={editing === "new" ? "Nuova categoria" : "Modifica categoria"} onClose={() => setEditing(null)}><div className="space-y-4"><FormField label="Nome" required><input autoFocus className={inputClass} value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} /></FormField><FormField label="Descrizione"><textarea className={`${inputClass} min-h-24`} value={form.descrizione} onChange={(e) => setForm({ ...form, descrizione: e.target.value })} /></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="Categoria principale"><select className={inputClass} value={form.parent_id} onChange={(e) => setForm({ ...form, parent_id: e.target.value })}><option value="">Nessuna (categoria principale)</option>{items.filter((x) => x.id !== (editing !== "new" ? editing.id : "")).map((x) => <option key={x.id} value={x.id}>{x.nome}</option>)}</select></FormField><FormField label="Colore"><div className="flex gap-2"><input type="color" className="h-11 w-14 rounded-xl border border-[#2B2F5E]/15 p-1" value={form.colore} onChange={(e) => setForm({ ...form, colore: e.target.value })} /><input className={inputClass} value={form.colore} onChange={(e) => setForm({ ...form, colore: e.target.value })} /></div></FormField></div><label className="flex items-center gap-2 text-sm text-[#2B2F5E]"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} className="accent-[#64B445]" />Categoria attiva</label><div className="flex justify-end gap-2"><button type="button" className={secondaryButton} onClick={() => setEditing(null)}>Annulla</button><button type="button" className={primaryButton} disabled={!form.nome.trim()} onClick={save}>Salva categoria</button></div></div></Modal>}
    {deleting && <Modal title="Eliminare la categoria?" onClose={() => setDeleting(null)}><p className="text-sm text-[#2B2F5E]/70"><strong>{deleting.nome}</strong> è collegata a {deleting.conteggio_rappresentanti || 0} rappresentanti, {deleting.conteggio_aziende || 0} aziende e {deleting.conteggio_prodotti || 0} prodotti.</p>{linked > 0 && <FormField label="Sostituisci con un’altra categoria (facoltativo)"><select className={`${inputClass} mt-4`} value={replacement} onChange={(e) => setReplacement(e.target.value)}><option value="">Rimuovi le associazioni</option>{items.filter((x) => x.id !== deleting.id && x.active).map((x) => <option key={x.id} value={x.id}>{x.nome}</option>)}</select></FormField>}<div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" className={secondaryButton} onClick={() => setDeleting(null)}>Annulla</button><button type="button" className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white" onClick={async () => { try { await eliminaCategoria(deleting.id, replacement || undefined); setDeleting(null); await load(); setToast({ message: replacement ? "Categoria sostituita ed eliminata." : "Categoria e associazioni rimosse." }); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore eliminazione.", error: true }); } }}> {replacement ? "Sostituisci ed elimina" : "Rimuovi associazioni ed elimina"}</button></div></Modal>}
    {toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}
  </LayoutApp>;
}
