"use client";

import { use, useEffect, useState } from "react";
import LayoutApp from "@/components/LayoutApp";
import AttachmentsManager from "@/components/rappresentanti/AttachmentsManager";
import { CompanyFormModal, ProductFormModal } from "@/components/rappresentanti/EntityForms";
import { BadgeList, Breadcrumb, EmptyState, LoadingSkeleton, PageHeader, SectionCard, StatusBadge, Toast, primaryButton, secondaryButton } from "@/components/rappresentanti/Common";
import { caricaAziende, caricaCategorie, caricaProdotti, caricaRappresentanti } from "@/lib/rappresentanti/api";
import type { AziendaRappresentata, CategoriaRappresentante, ProdottoRappresentato, Rappresentante } from "@/lib/rappresentanti/types";

export default function CompanyDetails({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [company, setCompany] = useState<AziendaRappresentata | null>(null); const [companies, setCompanies] = useState<AziendaRappresentata[]>([]); const [products, setProducts] = useState<ProdottoRappresentato[]>([]); const [reps, setReps] = useState<Rappresentante[]>([]); const [categories, setCategories] = useState<CategoriaRappresentante[]>([]); const [loading, setLoading] = useState(true); const [edit, setEdit] = useState(false); const [newProduct, setNewProduct] = useState(false); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const load = () => Promise.all([caricaAziende(), caricaProdotti(), caricaRappresentanti(), caricaCategorie(false)]).then(([a, p, r, c]) => { setCompanies(a); setCompany(a.find((x) => x.id === id) || null); setProducts(p.filter((x) => x.azienda_id === id)); setReps(r.filter((x) => x.aziende.some((rel) => rel.azienda_id === id))); setCategories(c); }).catch((e) => setToast({ message: e.message, error: true })).finally(() => setLoading(false)); useEffect(() => { load(); }, [id]);
  if (loading) return <LayoutApp><LoadingSkeleton rows={5} /></LayoutApp>; if (!company) return <LayoutApp><EmptyState title="Azienda non trovata." /></LayoutApp>;
  return <LayoutApp><Breadcrumb items={[{ label: "Rubrica rappresentanti", href: "/rubrica/rappresentanti" }, { label: "Aziende", href: "/rubrica/rappresentanti/aziende" }, { label: company.nome_commerciale || company.ragione_sociale }]} /><PageHeader title={company.nome_commerciale || company.ragione_sociale} subtitle={company.nome_commerciale ? company.ragione_sociale : company.descrizione || undefined} actions={<><StatusBadge active={company.active} /><button type="button" className={secondaryButton} onClick={() => setEdit(true)}>Modifica azienda</button><button type="button" className={primaryButton} onClick={() => setNewProduct(true)}>Nuovo prodotto</button></>} />
    <div className="grid gap-4 xl:grid-cols-3"><SectionCard title="Anagrafica"><dl className="space-y-3 text-sm"><Info label="Partita IVA" value={company.partita_iva} /><Info label="Codice fiscale" value={company.codice_fiscale} /><Info label="Email" value={company.email} href={company.email ? `mailto:${company.email}` : undefined} /><Info label="PEC" value={company.pec} href={company.pec ? `mailto:${company.pec}` : undefined} /><Info label="Telefono" value={company.telefono} href={company.telefono ? `tel:${company.telefono}` : undefined} /><Info label="Sito web" value={company.sito_web} href={company.sito_web || undefined} /></dl></SectionCard><SectionCard title="Sede"><dl className="space-y-3"><Info label="Indirizzo" value={company.indirizzo} /><Info label="Comune" value={company.comune} /><Info label="Provincia" value={company.provincia} /><Info label="Regione" value={company.regione} /><Info label="Nazione" value={company.nazione} /></dl></SectionCard><SectionCard title="Categorie"><BadgeList items={company.categorie.map((x) => ({ id: x.id, label: x.nome, color: x.colore }))} max={8} />{company.note && <p className="mt-5 whitespace-pre-wrap text-sm text-[#2B2F5E]/70">{company.note}</p>}</SectionCard></div>
    <SectionCard title={`Rappresentanti collegati (${reps.length})`} className="mt-4">{reps.length === 0 ? <p className="text-sm text-[#2B2F5E]/50">Nessun rappresentante collegato.</p> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reps.map((r) => { const rel = r.aziende.find((x) => x.azienda_id === id); return <a key={r.id} href={`/rubrica/rappresentanti/${r.id}`} className="rounded-xl border border-[#2B2F5E]/8 p-4 hover:border-[#5E9AD3]/40 hover:bg-[#5E9AD3]/5"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-[#2B2F5E]">{r.nome} {r.cognome}</p><p className="text-xs text-[#2B2F5E]/45">{r.ruolo || "—"}</p></div><StatusBadge active={rel?.active ?? r.active} label={rel?.stato_collaborazione} /></div><p className="mt-3 text-xs text-[#2B2F5E]/60">{rel?.area_territoriale || r.area_competenza || "Area non indicata"}</p></a>; })}</div>}</SectionCard>
    <SectionCard title={`Prodotti e linee (${products.length})`} className="mt-4">{products.length === 0 ? <p className="text-sm text-[#2B2F5E]/50">Nessun prodotto censito.</p> : <div className="overflow-x-auto"><table className="min-w-[650px] w-full text-sm"><thead className="text-left text-xs text-[#2B2F5E]/45"><tr><th className="pb-3">Prodotto</th><th className="pb-3">Codice</th><th className="pb-3">Categorie</th><th className="pb-3">Stato</th></tr></thead><tbody className="divide-y divide-[#2B2F5E]/8">{products.map((p) => <tr key={p.id}><td className="py-3"><p className="font-medium text-[#2B2F5E]">{p.nome}</p><p className="text-xs text-[#2B2F5E]/45">{p.descrizione}</p></td><td className="py-3">{p.codice || "—"}</td><td className="py-3"><BadgeList items={p.categorie.map((x) => ({ id: x.id, label: x.nome, color: x.colore }))} /></td><td className="py-3"><StatusBadge active={p.active} /></td></tr>)}</tbody></table></div>}</SectionCard>
    <SectionCard title="Allegati azienda" className="mt-4"><AttachmentsManager owner={{ azienda_id: id }} /></SectionCard>
    {edit && <CompanyFormModal initial={company} categories={categories} onClose={() => setEdit(false)} onSaved={async () => { setEdit(false); await load(); setToast({ message: "Azienda aggiornata." }); }} />}{newProduct && <ProductFormModal companies={companies} categories={categories} defaultCompanyId={id} onClose={() => setNewProduct(false)} onSaved={async () => { setNewProduct(false); await load(); setToast({ message: "Prodotto creato." }); }} />}{toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}</LayoutApp>;
}

function Info({ label, value, href }: { label: string; value: string | null | undefined; href?: string }) { return <div><dt className="text-xs text-[#2B2F5E]/45">{label}</dt><dd className="mt-0.5 break-words font-medium text-[#2B2F5E]">{value ? href ? <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="text-[#2D80B3] hover:underline">{value}</a> : value : "—"}</dd></div>; }
