"use client";

import { useEffect, useMemo, useState } from "react";
import LayoutApp from "@/components/LayoutApp";
import { ProductFormModal } from "@/components/rappresentanti/EntityForms";
import { BadgeList, Breadcrumb, EmptyState, LoadingSkeleton, Modal, PageHeader, StatCard, StatusBadge, Toast, inputClass, primaryButton, secondaryButton } from "@/components/rappresentanti/Common";
import { caricaAziende, caricaCategorie, caricaProdotti, caricaRappresentanti, eliminaProdotto } from "@/lib/rappresentanti/api";
import type { AziendaRappresentata, CategoriaRappresentante, ProdottoRappresentato, Rappresentante } from "@/lib/rappresentanti/types";

export default function ProductsPage() {
  const [items, setItems] = useState<ProdottoRappresentato[]>([]); const [companies, setCompanies] = useState<AziendaRappresentata[]>([]); const [categories, setCategories] = useState<CategoriaRappresentante[]>([]); const [representatives, setRepresentatives] = useState<Rappresentante[]>([]); const [search, setSearch] = useState(""); const [company, setCompany] = useState(""); const [category, setCategory] = useState(""); const [representative, setRepresentative] = useState(""); const [status, setStatus] = useState("tutti"); const [editing, setEditing] = useState<ProdottoRappresentato | "new" | null>(null); const [deleting, setDeleting] = useState<ProdottoRappresentato | null>(null); const [loading, setLoading] = useState(true); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null);
  const load = () => Promise.all([caricaProdotti(), caricaAziende(), caricaCategorie(false), caricaRappresentanti()]).then(([p, a, c, r]) => { setItems(p); setCompanies(a); setCategories(c); setRepresentatives(r); }).catch((e) => setToast({ message: e.message, error: true })).finally(() => setLoading(false)); useEffect(() => { load(); }, []);
  const filtered = useMemo(() => items.filter((x) => { const text = [x.nome, x.codice, x.descrizione, x.azienda?.ragione_sociale, ...x.categorie.map((c) => c.nome)].filter(Boolean).join(" ").toLowerCase(); return (!search || text.includes(search.toLowerCase())) && (!company || x.azienda_id === company) && (!category || x.categorie.some((c) => c.id === category)) && (!representative || representatives.find((r) => r.id === representative)?.prodotti.some((p) => p.id === x.id)) && (status === "tutti" || (status === "attivi" ? x.active : !x.active)); }), [items, search, company, category, representative, status, representatives]);
  const repCount = (id: string) => representatives.filter((r) => r.prodotti.some((p) => p.id === id)).length;
  return <LayoutApp><Breadcrumb items={[{ label: "Rubrica rappresentanti", href: "/rubrica/rappresentanti" }, { label: "Prodotti e linee" }]} /><PageHeader title="Prodotti e linee" subtitle="Catalogo relazionale dei prodotti, collegato ad aziende, categorie e rappresentanti." actions={<button type="button" className={primaryButton} onClick={() => setEditing("new")}>Nuovo prodotto</button>} /><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><StatCard label="Prodotti censiti" value={items.length} tone="gold" /><StatCard label="Prodotti attivi" value={items.filter((x) => x.active).length} tone="green" /><StatCard label="Aziende produttrici" value={new Set(items.map((x) => x.azienda_id)).size} /></div><div className="mb-4 grid gap-3 rounded-2xl border border-[#2B2F5E]/8 bg-white p-4 md:grid-cols-2 xl:grid-cols-5"><input className={inputClass} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cerca prodotto..." /><select className={inputClass} value={company} onChange={(e) => setCompany(e.target.value)}><option value="">Tutte le aziende</option>{companies.map((x) => <option key={x.id} value={x.id}>{x.nome_commerciale || x.ragione_sociale}</option>)}</select><select className={inputClass} value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Tutte le categorie</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.nome}</option>)}</select><select className={inputClass} value={representative} onChange={(e) => setRepresentative(e.target.value)}><option value="">Tutti i rappresentanti</option>{representatives.map((x) => <option key={x.id} value={x.id}>{x.cognome} {x.nome}</option>)}</select><select className={inputClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="tutti">Tutti gli stati</option><option value="attivi">Attivi</option><option value="non_attivi">Non attivi</option></select></div>
    {loading ? <LoadingSkeleton rows={5} /> : filtered.length === 0 ? <EmptyState title="Nessun prodotto trovato." actionLabel={!items.length ? "Aggiungi il primo prodotto" : undefined} onAction={!items.length ? () => setEditing("new") : undefined} /> : <div className="overflow-x-auto rounded-2xl border border-[#2B2F5E]/8 bg-white"><table className="min-w-[900px] w-full text-sm"><thead className="bg-[#F7F8FA] text-left text-xs text-[#2B2F5E]/55"><tr><th className="p-4">Prodotto</th><th className="p-4">Azienda</th><th className="p-4">Categorie</th><th className="p-4">Rappresentanti</th><th className="p-4">Stato</th><th className="p-4 text-right">Azioni</th></tr></thead><tbody className="divide-y divide-[#2B2F5E]/8">{filtered.map((x) => <tr key={x.id}><td className="p-4"><p className="font-semibold text-[#2B2F5E]">{x.nome}</p><p className="text-xs text-[#2B2F5E]/45">{x.codice || x.descrizione || "—"}</p></td><td className="p-4"><a href={`/rubrica/rappresentanti/aziende/${x.azienda_id}`} className="font-medium text-[#2D80B3] hover:underline">{x.azienda?.nome_commerciale || x.azienda?.ragione_sociale || "—"}</a></td><td className="p-4"><BadgeList items={x.categorie.map((c) => ({ id: c.id, label: c.nome, color: c.colore }))} max={3} /></td><td className="p-4 text-[#2B2F5E]">{repCount(x.id)}</td><td className="p-4"><StatusBadge active={x.active} /></td><td className="p-4"><div className="flex justify-end gap-2">{x.link_prodotto && <a target="_blank" rel="noreferrer" href={x.link_prodotto} className={`${secondaryButton} min-h-9 py-1.5 text-xs`}>Apri</a>}<button type="button" className={`${secondaryButton} min-h-9 py-1.5 text-xs`} onClick={() => setEditing(x)}>Modifica</button><button type="button" className="min-h-9 rounded-xl px-3 text-xs font-semibold text-red-600 hover:bg-red-50" onClick={() => setDeleting(x)}>Elimina</button></div></td></tr>)}</tbody></table></div>}
    {editing && <ProductFormModal initial={editing === "new" ? undefined : editing} companies={companies} categories={categories} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); setToast({ message: "Prodotto salvato." }); }} />}{deleting && <Modal title="Eliminare il prodotto?" onClose={() => setDeleting(null)}><p className="text-sm text-[#2B2F5E]/70">Il prodotto può essere eliminato solo se non è associato a rappresentanti.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={secondaryButton} onClick={() => setDeleting(null)}>Annulla</button><button type="button" className="min-h-11 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white" onClick={async () => { try { await eliminaProdotto(deleting.id); setDeleting(null); await load(); setToast({ message: "Prodotto eliminato." }); } catch (e) { setToast({ message: e instanceof Error ? e.message : "Errore eliminazione.", error: true }); } }}>Elimina</button></div></Modal>}{toast && <Toast message={toast.message} error={toast.error} onClose={() => setToast(null)} />}</LayoutApp>;
}
